### ISSUE TITLE
Confusion about main.lua

### ISSUE THREAD

**Issue by sunshineatnoon** [fxia22/pldtgan#1]
Hi, thanks for opensource this project.
I have some confusions about line 283 in main.lua:
`local df_dg = netD:updateGradInput(input_img, df_do)`

When you do backpropagation wrt to D, shouldn't you backpropagate to fake image? It seems that you backpropagate to input image here.

**Comment by fxia22** [comment]
Hi, @sunshineatnoon thank you for your feedback. I was busy on other projects so didn't have time to fix it until now. Now it's fixed, I have tested and it works well on LOOKBOOK dataset (will post results in a day or two). Let's me know if there are any further issues. 

Cheers,
Fei

**Comment by sunshineatnoon** [comment]
Cool, Thanks!
