### ISSUE TITLE
released training utility enhanced version of this repo

### ISSUE THREAD

**Issue by nashory** [fxia22/pldtgan#2]
I had lots of trouble with running this code and found this code has some bugs (e.g. no image padding function which leads to dimension match error.)
Also it was a bit inconvenient to change training parameters.
Instead, I forked this repo and made a bug-fixed, utility enhanced version.
It seems the code works well, so if you are seeking any working code of this paper please refer here.
(https://github.com/nashory/pixel-level-dt-torch)

**Comment by fxia22** [comment]
Can you create pull request? Thanks

**Comment by fxia22** [comment]
Can you open issues about bugs? So that I can fix those and help people reproduce the paper.
